name: Build and Validate PR

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test-and-build:
    name: Test, Validate, and Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
      - name: Run unit tests
        run: npm test
        
      - name: Run integration tests
        run: npm run test:integration
        
      - name: Test coverage
        run: npm run test:coverage
        continue-on-error: true
        
      - name: Validate action.yml
        run: |
          if [ -f "action.yml" ]; then
            echo "✅ action.yml found"
            python -c "import yaml; yaml.safe_load(open('action.yml'))" || exit 1
            echo "✅ action.yml is valid YAML"
          fi
          
      - name: Check required files
        run: |
          echo "Checking required files..."
          test -f "package.json" && echo "✅ package.json exists"
          test -f "README.md" && echo "✅ README.md exists"
          
          if [ -d "__tests__" ] || [ -d "test" ] || [ -d "tests" ]; then
            echo "✅ Test directory found"
          else
            echo "❌ No test directory found"
            exit 1
          fi
        
      - name: Build action
        run: npm run build
        
      - name: Check for dist changes
        if: github.event_name == 'pull_request'
        id: check-changes
        run: |
          if git diff --quiet dist/; then
            echo "has-changes=false" >> $GITHUB_OUTPUT
            echo "No changes to dist/"
          else
            echo "has-changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected in dist/"
          fi
          
      - name: Commit built files
        if: github.event_name == 'pull_request' && steps.check-changes.outputs.has-changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/
          git commit -m "build: update dist for PR changes"
          git push
          
      - name: Comment on PR
        if: github.event_name == 'pull_request' && steps.check-changes.outputs.has-changes == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 **Auto-build**: Updated `dist/` folder with latest changes.'
            })
